# permissions for end users to edit pushencryptedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pushencryptedsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: encryptor
    app.kubernetes.io/part-of: encryptor
    app.kubernetes.io/managed-by: kustomize
  name: pushencryptedsecret-editor-role
rules:
- apiGroups:
  - encryptor.k8s.io
  resources:
  - pushencryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - encryptor.k8s.io
  resources:
  - pushencryptedsecrets/status
  verbs:
  - get
