# permissions for end users to view pushencryptedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pushencryptedsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: encryptor
    app.kubernetes.io/part-of: encryptor
    app.kubernetes.io/managed-by: kustomize
  name: pushencryptedsecret-viewer-role
rules:
- apiGroups:
  - encryptor.dev
  resources:
  - pushencryptedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - encryptor.dev
  resources:
  - pushencryptedsecrets/status
  verbs:
  - get
