---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - encryptor.k8s.io
  resources:
  - pushencryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - encryptor.k8s.io
  resources:
  - pushencryptedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - encryptor.k8s.io
  resources:
  - pushencryptedsecrets/status
  verbs:
  - get
  - patch
  - update
