# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pushencryptedsecrets.encryptor.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: encryptor-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
